# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_out <- function(y, m, initstate, errortype, trendtype, seasontype, damped, alpha, beta, gamma, phi, nmse, k) {
    .Call('robets_calc_out', PACKAGE = 'robets', y, m, initstate, errortype, trendtype, seasontype, damped, alpha, beta, gamma, phi, nmse, k)
}

tau2 <- function(x) {
    .Call('robets_tau2', PACKAGE = 'robets', x)
}

